Check TZ environment variable is valid #18

diff --git a/dockerfiles/phpipam-base/root/set_timezone b/dockerfiles/phpipam-base/root/set_timezone
--- a/dockerfiles/phpipam-base/root/set_timezone
+++ b/dockerfiles/phpipam-base/root/set_timezone
@@ -1,8 +1,19 @@
-#!/bin/sh
+#!/bin/ash
+
+if [ -z "$TZ" ]; then
+  echo "Info: Please configure timezone (env TZ), defaulting to UTC"
+  echo "Info: See supported environment variables https://hub.docker.com/r/phpipam/phpipam-www"
+  export TZ="UTC"
+fi
+
 
 if [ -f /usr/share/zoneinfo/$TZ ]; then
+  echo "Info: Setting timezone to $TZ"
   setup-timezone -z $TZ
   echo -e "[Date]\ndate.timezone = $TZ" >/etc/php7/conf.d/99_tz.ini
+  exit 0
 else
-  echo -e "[Date]\ndate.timezone = UTC" >/etc/php7/conf.d/99_tz.ini
+  echo "Error: Timezone TZ=\"$TZ\" not found in /usr/share/zoneinfo"
+  echo "Info: See supported environment variables https://hub.docker.com/r/phpipam/phpipam-www"
+  exit 1
 fi
